/* ============================================================================
   ontdekken-inhoud.js — de teksten van de Ontdekken-hub
   ----------------------------------------------------------------------------
   Alleen inhoud, geen logica. De rubriekenstructuur staat in script.js
   (ontdekRubrieken); dit bestand levert de blokken waar die naar verwijst.
   Wordt vóór script.js ingeladen en draagt hetzelfde cache-busternummer als
   style.css, lang/nl.js en script.js.

   Twee vormen:

     lexicon   een lijst regels, elk in een van twee vormen:
                 { term, uitleg[, bijbelplaats] }   een gewone regel
                 { term, verwijstNaar }             toont de regel met dezelfde
                                                    term uit het lexicon-
                                                    onderwerp met dat id
               Zo staat een tekst maar op één plek en verschijnt hij toch in
               twee lijsten. bijbelplaats is optioneel.
               Elk woord dat ergens achter "Zie ook:" staat, moet in het
               woordenboek te vinden zijn: als eigen term of als verwijzing
               (verwijstNaar). Zo is het woordenboek de plek waar alles op te
               zoeken is.

     artikel   een lijst getypeerde blokken; elk blok rendert op een bestaande
               CSS-klasse, dus er is geen nieuwe opmaak nodig:
                 { kader: "…" }   .naslag-kadertje
                 { kop:   "…" }   h3.naslag-kop
                 { item:  "…" }   p.naslag-item   (mag inline HTML bevatten)
                 { noot:  "…" }   p.naslag-noot
                 { tabel: { koppen: […], rijen: [[…]] } }   table.naslag-tabel
   ========================================================================== */

/* eslint-disable no-unused-vars */

// --- Woorden: het woordenboek (56 termen, alfabetisch) ----------------------
const ONTDEK_WOORDENBOEK = [
    { term: "Allerheiligste", uitleg: "Het meest heilige, afgesloten deel binnen in de tempel. Volgens de traditie was God daar zelf aanwezig, en alleen de hogepriester mocht er binnen." },
    { term: "Altaar", uitleg: "Een verhoogde plek, vaak van steen, waar offers aan God werden gebracht." },
    { term: "Apostel", verwijstNaar: "wie-gemeenten" },
    { term: "Bekering", uitleg: "Je leven omdraaien: stoppen met de verkeerde kant op gaan en kiezen om het goede te doen, en zo bij God gaan horen. Je kunt het zien als een ommekeer van 180 graden — je loopt letterlijk de andere kant op. In de Bijbel hoort daar vaak spijt bij over wat je fout deed, en het verlangen om opnieuw te beginnen." },
    { term: "Bezonnenheid", uitleg: "Rustig en verstandig nadenken voordat je iets zegt of doet, en je niet laten meeslepen door angst of boosheid. Paulus schrijft aan Timoteüs dat God ons een geest van kracht, liefde en bezonnenheid heeft gegeven." },
    { term: "Bisschop", uitleg: "Een leider in de kerk. Het woord komt via het Latijn van het Griekse <em>episkopos</em>: iemand die toezicht houdt. In de Katholieke Kerk leidt een bisschop een bisdom, een gebied met veel parochies, zoals een herder die voor een grote kudde zorgt. Katholieken zien de bisschoppen als opvolgers van de apostelen. De bisschop van Rome is de paus. Een bisschop draagt bij plechtige vieringen een mijter (een hoge, puntige muts) en een staf die op een herdersstaf lijkt. Sint-Nicolaas was ook bisschop, in de stad Myra in het huidige Turkije. Daarom heeft Sinterklaas een mijter en een staf. Ook de orthodoxe kerken en sommige protestantse kerken kennen bisschoppen. <em>Zie ook: opziener, apostel.</em>" },
    { term: "Discipel (leerling)", verwijstNaar: "wie-gemeenten" },
    { term: "Eeuwig leven", uitleg: "Leven dat nooit ophoudt, samen met God — ook na de dood." },
    { term: "Evangelie", uitleg: "Het woord betekent \"goed nieuws\". Het zijn ook de vier boeken die het leven van Jezus vertellen: Matteüs, Marcus, Lucas en Johannes. Elke schrijver kreeg later zijn eigen symbool — de mens, de leeuw, de stier en de adelaar — precies de tekens die je in dit spel als trofee kunt verdienen." },
    { term: "Farizeeën", verwijstNaar: "wie-groepen" },
    { term: "Gelijkenis", uitleg: "Een kort verhaaltje dat Jezus vertelde om iets groots uit te leggen met iets gewoons. Door over schapen, zaadjes of een verloren muntje te vertellen, maakte Hij een diepe les ineens begrijpelijk. Het bekendste voorbeeld is misschien wel het verhaal van de verloren zoon." },
    { term: "Gemeente", uitleg: "In de Bijbel is een gemeente de groep christenen die in één stad bij elkaar hoort, bijvoorbeeld \"de gemeente in Filippi\". Er waren toen nog geen kerkgebouwen: de mensen kwamen gewoon bij elkaar thuis. Vandaag gebruiken christenen hier twee woorden voor. Sommige groepen noemen zich een kerk — bijvoorbeeld de Katholieke Kerk, de Protestantse Kerk of de Orthodoxe Kerk. Andere groepen noemen zich een gemeente — bijvoorbeeld evangelische gemeenten, baptistengemeenten en pinkstergemeenten. Allebei is goed. Het gaat namelijk niet om het gebouw of om de naam, maar om de mensen die samen bij Jezus horen. En dat zijn ze allemaal. <em>Zie ook: kerk.</em>" },
    { term: "Genade", uitleg: "Iets goeds krijgen wat je niet verdiend hebt; onverdiende vriendelijkheid. Het is een cadeau, geen beloning — je hoeft er niets voor te presteren. In de Bijbel gaat het vaak over Gods genade: dat Hij goed is voor mensen, ook als ze het niet \"verdiend\" hebben." },
    { term: "Gerechtigheid", uitleg: "Doen wat goed en rechtvaardig is in de ogen van God; eerlijk en goed omgaan met andere mensen." },
    { term: "Godvrezenden", verwijstNaar: "wie-groepen" },
    { term: "Heidenen", verwijstNaar: "wie-groepen" },
    { term: "Heilige Geest", uitleg: "De Heilige Geest is God zelf: de derde persoon van de Drie-eenheid. Christenen geloven in één God in drie personen — de Vader, de Zoon (Jezus) en de Heilige Geest — die samen tóch één God zijn. De Heilige Geest werkt in mensen: Hij geeft moed en troost en helpt hen om dichter bij God te leven. Je kunt Hem niet zien, net zomin als je de wind ziet, maar je merkt wel wat Hij doet." },
    { term: "Hemelvaart", uitleg: "Het moment waarop Jezus, na Zijn opstanding, omhoogging naar de hemel en niet langer op aarde bij Zijn leerlingen bleef. Christenen herdenken dit op Hemelvaartsdag — voor veel kinderen ook gewoon een vrije donderdag." },
    { term: "Hogepriester", verwijstNaar: "wie-tempel" },
    { term: "Kerk", uitleg: "Het woord kerk betekent twee dingen. Het is het gebouw waar christenen samenkomen. Maar het is vooral de groep mensen zelf: de kerk zijn de christenen, niet de stenen. In het Grieks, de taal waarin het Nieuwe Testament is geschreven, staat er <span class=\"grieks\">ἐκκλησία</span> (<em>ekklèsia</em>). Dat betekent letterlijk \"de groep die bij elkaar geroepen is\" — van <em>ek</em> (\"uit\") en <em>kaleō</em> (\"roepen\"). In een Griekse stad was de <em>ekklèsia</em> de vergadering van alle burgers, die met een roep bijeen werd geroepen. Paulus gebruikt datzelfde woord voor de christenen: mensen die door God bij elkaar geroepen zijn. In onze Bijbel wordt <em>ekklèsia</em> soms vertaald met \"gemeente\" en soms met \"kerk\" — het is dus hetzelfde woord. Ons woord kerk komt van een ánder Grieks woord: <span class=\"grieks\">κυριακόν</span> (<em>kuriakon</em>). Dat betekent \"wat van de Heer is\", van <em>kurios</em>, \"Heer\". Toen de christenen na een paar honderd jaar eigen gebouwen kregen om in samen te komen, noemden ze zo'n gebouw het <em>kuriakon</em>: het huis van de Heer. Dat woord reisde mee naar het noorden van Europa en werd daar kerk — en ook het Duitse <em>Kirche</em> en het Engelse <em>church</em>. Grappig genoeg had het Grieks dus twee woorden: <em>ekklèsia</em> voor de mensen en <em>kuriakon</em> voor het gebouw. Wij hebben daar één woord van gemaakt. Als je \"kerk\" zegt, kun je dus allebei bedoelen — en meestal bedoelen we de mensen. <em>Zie ook: gemeente.</em>" },
    { term: "Koninkrijk van God", uitleg: "Niet een land dat je op de kaart kunt aanwijzen, maar een manier om te zeggen: daar waar God de koning is en alles goed en eerlijk gaat. Jezus sprak er heel vaak over. Soms heet het ook \"het hemelrijk\" of \"het koninkrijk der hemelen\"." },
    { term: "Kruisiging", uitleg: "Een wrede Romeinse straf waarbij iemand aan een kruis werd vastgemaakt. Jezus werd op deze manier ter dood gebracht." },
    { term: "Leviet", verwijstNaar: "wie-tempel" },
    { term: "Martelaar", uitleg: "Iemand die aan zijn geloof vasthoudt, zelfs als hij daarvoor gedood wordt. Stefanus was de eerste in de vroege kerk." },
    { term: "Messias", uitleg: "Een Hebreeuws woord dat \"de gezalfde\" betekent: iemand die met olie gezalfd werd als teken dat God hem uitkoos, zoals vroeger bij koningen. De Messias is de beloofde redder op wie het volk lang wachtte. Christenen geloven dat Jezus die Messias is. In het Grieks heet \"de gezalfde\" trouwens \"Christus\" — dus Messias en Christus betekenen precies hetzelfde, alleen in een andere taal." },
    { term: "Offer", uitleg: "Iets waardevols dat je aan God geeft. Vroeger was dat vaak een dier, dat op het altaar in de tempel werd gebracht." },
    { term: "Openbaring", uitleg: "Iets wat God laat zien of bekendmaakt dat mensen uit zichzelf niet konden weten. Het is ook de naam van het laatste boek van de Bijbel." },
    { term: "Opstanding", uitleg: "Weer levend worden na de dood. Het bekendste voorbeeld is Jezus, die volgens de evangeliën op de derde dag na Zijn dood weer opstond — dat vieren christenen met Pasen. Het is het grote keerpunt waar de evangeliën naartoe werken." },
    { term: "Opziener", verwijstNaar: "wie-gemeenten" },
    { term: "Oudste (ouderling)", verwijstNaar: "wie-gemeenten" },
    { term: "Pasen (Pesach)", uitleg: "Pesach is het Joodse feest waarop het volk viert dat God hen lang geleden uit de slavernij in Egypte bevrijdde. Jezus vierde dit feest ook. Voor christenen kreeg Pasen er later een tweede betekenis bij: het feest van Jezus' opstanding." },
    { term: "Perkament", uitleg: "Dun bewerkte dierenhuid waarop vroeger werd geschreven. Het was sterker en duurzamer dan papyrus. In 2 Timoteüs vraagt Paulus of Timoteüs de boekrollen en vooral de perkamenten wil meebrengen." },
    { term: "Priester", verwijstNaar: "wie-tempel" },
    { term: "Profeet", verwijstNaar: "wie-gemeenten" },
    { term: "Proselieten", verwijstNaar: "wie-groepen" },
    { term: "Rechtvaardig", uitleg: "Eerlijk en betrouwbaar; iemand die anderen eerlijk behandelt en leeft zoals God het bedoelt." },
    { term: "Sabbat", uitleg: "De vaste rustdag in de week, voor Joden de zaterdag. Op die dag werkten de mensen niet, maar namen ze tijd voor God en voor rust. Er waren strenge regels over wat wel en niet mocht — zo streng zelfs dat sommigen vonden dat Jezus de regels overtrad toen Hij op de sabbat iemand beter maakte." },
    { term: "Sadduceeën", verwijstNaar: "wie-groepen" },
    { term: "Schriftgeleerde", verwijstNaar: "wie-tempel" },
    { term: "Stadhouder (landvoogd)", verwijstNaar: "wie-bestuur" },
    { term: "Synagoge", uitleg: "Het gebouw waar Joodse mensen bij elkaar kwamen om te bidden, te leren en uit de heilige boeken te lezen. Anders dan de tempel was er niet één synagoge, maar stond er in bijna elk dorp en elke stad een. Jezus kwam er vaak en leerde er de mensen. Het Griekse woord <em>synagōgē</em> betekent \"bijeenkomst\": eerst de mensen die samenkwamen, later ook het gebouw." },
    { term: "Tempel", uitleg: "Het grote, heilige gebouw in Jeruzalem waar de mensen God vereerden. Let op het verschil met een synagoge: synagogen stonden in elk dorp, maar dé tempel was er maar één. In de geschiedenis waren er eigenlijk twee. De eerste werd rond 960 v.Chr. gebouwd door koning Salomo en in 586 v.Chr. verwoest door de Babyloniërs. De tweede werd na de ballingschap herbouwd — voltooid rond 515 v.Chr., onder leiding van Zerubbabel — en eeuwen later door koning Herodes enorm vergroot en verfraaid; dát is de tempel uit Jezus' tijd. In het jaar 70 n.Chr. verwoestten de Romeinen ook die. Zou er ooit een nieuwe tempel komen, dan zou dat dus de derde tempel zijn." },
    { term: "Tetrarch (viervorst)", verwijstNaar: "wie-bestuur" },
    { term: "Tollenaar", verwijstNaar: "wie-beroepen" },
    { term: "Vasten", uitleg: "Een tijd lang niet of veel minder eten, om je aandacht helemaal op God te richten." },
    { term: "Verbond", uitleg: "Een bijzondere, plechtige afspraak tussen God en de mensen — sterker dan een gewone belofte, meer als een blijvende band. De Bijbel vertelt over verschillende verbonden, bijvoorbeeld met Noach en met Abraham. Jezus sprak bij het Laatste Avondmaal over een \"nieuw verbond\"." },
    { term: "Vergeving", uitleg: "Niet boos blijven over iets wat verkeerd is gedaan, maar het loslaten en opnieuw beginnen." },
    { term: "Verkondigen", uitleg: "Het goede nieuws over God en Jezus aan mensen vertellen, zodat zo veel mogelijk mensen het horen." },
    { term: "Verzoeking", uitleg: "De aandrang om iets te doen waarvan je diep vanbinnen weet dat het niet goed is." },
    { term: "Wet (de Wet)", uitleg: "De regels die God volgens de Bijbel via Mozes aan het volk Israël gaf, zoals de Tien Geboden. Met \"de Wet\" worden soms ook de eerste boeken van de Bijbel bedoeld, waarin die regels staan. Joden in Jezus' tijd hechtten er veel waarde aan om volgens de Wet te leven." },
    { term: "Wijzen uit het oosten", verwijstNaar: "wie-groepen" },
    { term: "Wonder", uitleg: "Iets bijzonders dat je niet op een gewone manier kunt verklaren, en dat laat zien hoe groot Gods kracht is. In de evangeliën doet Jezus veel wonderen: Hij maakt zieken beter, stilt een storm en geeft blinden hun zicht terug. Een wonder is in de Bijbel meestal ook een teken: het wil iets duidelijk maken." },
    { term: "Zaligspreking", uitleg: "Een van de uitspraken van Jezus die begint met \"Gelukkig zijn zij die…\", over wie het bij God écht goed heeft. Jezus sprak ze uit tijdens een beroemde toespraak op een berg, de Bergrede. Vaak draaien ze de gewone verwachting om: juist wie het moeilijk heeft, wordt gelukkig genoemd." },
    { term: "Zegenen", uitleg: "Iemand namens God het goede toewensen, vaak met woorden of met een hand op het hoofd." },
    { term: "Zendeling", uitleg: "Iemand die op reis gaat, vaak ver van huis, om anderen over Jezus te vertellen. Paulus was zo iemand." },
    { term: "Zonde", uitleg: "Alles wat stukgaat tussen mensen onderling en tussen mensen en God: iets verkeerds doen, tegen wat goed is en tegen wat God wil. Het oude woord betekent eigenlijk \"je doel missen\" — alsof je met een pijl op de roos mikt en er net naast schiet." },
];
// --- Wie is wie: Tempel en synagoge (13 termen, alfabetisch) ----------------
const ONTDEK_WIE_TEMPEL = [
    { term: "Geldwisselaar", uitleg: "Pelgrims kwamen van heinde en verre naar de tempel in Jeruzalem en hadden geld uit allerlei landen bij zich. De tempelbelasting moest echter met één bepaald soort zilveren munt worden betaald. Geldwisselaars wisselden het geld om, tegen betaling, en zaten met hun tafels in de voorhof van de tempel. Jezus gooide hun tafels om, omdat het huis van Zijn Vader geen markt mocht zijn.", bijbelplaats: "Johannes 2:14-16 · Matteüs 17:24; 21:12" },
    { term: "Hoge Raad (Sanhedrin)", uitleg: "De hoogste Joodse raad, in Jeruzalem. Het woord Sanhedrin komt van het Griekse <em>synedrion</em>: \"samen zitten\". Volgens de Joodse overlevering had hij eenenzeventig leden: hogepriesters, oudsten van het volk en schriftgeleerden, onder wie farizeeën en sadduceeën. De hogepriester was de voorzitter. De raad besliste over geloofszaken en rechtszaken onder Joden, maar de Romeinen hadden het laatste woord. Jezus moest zich voor de Hoge Raad verantwoorden, en later ook Petrus, Johannes en Paulus. Nikodemus en Jozef van Arimatea zaten er zelf in.", bijbelplaats: "Marcus 14:55 · Lucas 23:50-51 · Johannes 3:1; 7:50 · Handelingen 5:27; 23:1" },
    { term: "Hogepriester", uitleg: "De belangrijkste priester, een soort baas van de tempel in Jeruzalem. Hij mocht als enige, en maar één keer per jaar, in het meest heilige deel van de tempel komen. Het Griekse woord is <em>archiereus</em>. Het begin, <em>archi-</em>, betekent \"hoogste\" of \"eerste\"; daar komt ons \"aarts-\" vandaan, zoals in aartsengel en aartsvader.", bijbelplaats: "Matteüs 26:57 · Hebreeën 9:7" },
    { term: "Hogepriesters (overpriesters)", uitleg: "Het meervoud van hogepriester. Toch was er maar één hogepriester tegelijk. Het meervoud gaat over een hele groep: de hogepriester van dat moment, de hogepriesters van vroeger zoals Annas, en de hoofden van de voornaamste priesterfamilies. Daarom zeggen sommige vertalingen hogepriesters en andere overpriesters. Samen hadden ze de leiding over de tempel en veel macht in Jeruzalem. Toen de wijzen uit het oosten naar de pasgeboren koning vroegen, riep koning Herodes de hogepriesters en schriftgeleerden bij elkaar om te horen waar de Messias geboren zou worden.", bijbelplaats: "Matteüs 2:4 · Johannes 18:13" },
    { term: "Leviet", uitleg: "Iemand uit de stam Levi. Levi was een van de twaalf zonen van Jakob, en zijn nakomelingen vormden een van de twaalf stammen van Israël. Mozes en zijn broer Aäron hoorden ook bij deze stam. God koos de stam Levi uit om Hem te dienen: eerst bij de heilige tent in de woestijn, de tabernakel, en later in de tempel. Daarom kregen de levieten in het beloofde land geen eigen stamgebied. Ze leefden van een tiende deel van de oogst, dat de andere stammen hun gaven. De nakomelingen van Aäron werden priester. De andere levieten hielpen in de tempel: ze bewaakten de poorten, zongen en maakten muziek, en zorgden dat alles klaarstond voor de diensten. In de gelijkenis van de barmhartige Samaritaan loopt een leviet de gewonde man voorbij. Barnabas, de reisgenoot van Paulus, was ook een leviet.", bijbelplaats: "Numeri 3:5-9; 18:21-24 · Lucas 10:32 · Handelingen 4:36" },
    { term: "Oudsten van het volk", uitleg: "De hoofden van de voorname families in Jeruzalem. Ze hadden gezag omdat ze ervaren en invloedrijk waren, en ze zaten samen met de hogepriesters en de schriftgeleerden in de Hoge Raad. In de evangeliën worden die drie groepen vaak samen genoemd. Het zijn andere oudsten dan in de eerste christelijke gemeenten. <em>Zie ook: ouderling.</em>", bijbelplaats: "Matteüs 21:23 · Marcus 11:27" },
    { term: "Priester", uitleg: "In de tijd van de Bijbel was een priester iemand die in de tempel dienst deed: hij bracht offers aan God en zegende het volk. De priesters waren allemaal nakomelingen van Aäron, de broer van Mozes. God had Aäron en zijn zonen uitgekozen als priesters, en dat ging over van vader op zoon. Aäron hoorde bij de stam Levi; de andere mannen uit die stam hielpen in de tempel als leviet. De belangrijkste van hen was de hogepriester. In de Katholieke Kerk is een priester vandaag iemand die gewijd is om de mis te leiden en te zorgen voor de gelovigen in een parochie. Ook de orthodoxe kerken kennen priesters. <em>Zie ook: hogepriester, leviet, tempel, offer.</em>", bijbelplaats: "Exodus 28:1 · Lucas 1:5, 8-9" },
    { term: "Rabbi (rabboeni)", uitleg: "Een aanspreekvorm die \"mijn meester\" of \"mijn leraar\" betekent, voor iemand die les gaf in de Schrift. De leerlingen van Jezus spraken Hem zo aan, en ook andere mensen deden dat. Rabboeni is een nog persoonlijkere vorm: zo noemde Maria Magdalena Jezus toen ze Hem na Zijn opstanding herkende. Nu is een rabbijn de leraar en leider van een Joodse gemeente.", bijbelplaats: "Johannes 1:38; 20:16" },
    { term: "Schriftgeleerde", uitleg: "Een echte kenner van de heilige boeken: iemand die ze van buiten kende en aan anderen uitlegde, een beetje als een professor van de Bijbel van toen. Schriftgeleerden hadden veel aanzien en kwamen in de evangeliën vaak in gesprek — en in discussie — met Jezus.", bijbelplaats: "Marcus 12:28" },
    { term: "Synagogedienaar", uitleg: "Een helper in de synagoge. Hij bewaarde de boekrollen, gaf ze aan wie ging voorlezen en borg ze daarna weer op. Toen Jezus in Nazaret uit de profeet Jesaja had voorgelezen, gaf Hij de rol terug aan de dienaar en ging zitten.", bijbelplaats: "Lucas 4:17, 20" },
    { term: "Synagogeoverste", uitleg: "De man die de leiding had over de synagoge, het gebouw waar Joden elke sabbat samenkwamen om te bidden en uit de Schrift te lezen. Hij zorgde dat de samenkomsten goed verliepen en vroeg wie er zou voorlezen of spreken. Een synagogeoverste was geen priester: priesters werkten alleen in de tempel in Jeruzalem. De bekendste synagogeoverste in de Bijbel is Jaïrus, die Jezus om hulp vroeg voor zijn dochtertje.", bijbelplaats: "Marcus 5:22 · Handelingen 13:15; 18:8" },
    { term: "Tempelwacht (tempeloverste)", uitleg: "De tempel in Jeruzalem had een eigen wacht van levieten. Zij bewaakten de poorten en zorgden voor orde. Hun hoofd was de tempeloverste, na de hogepriester een van de belangrijkste priesters. De tempelwacht was erbij toen Jezus gevangen werd genomen, en later namen ze ook de apostelen mee.", bijbelplaats: "Lucas 22:52 · Handelingen 4:1; 5:26" },
    { term: "Wetgeleerde", uitleg: "Iemand die de Wet van Mozes heel goed kende en uitlegde hoe je volgens die Wet moest leven. In de evangeliën betekent het bijna hetzelfde als schriftgeleerde; vooral Lucas gebruikt dit woord. Het was een wetgeleerde die Jezus vroeg: \"Wie is mijn naaste?\" Daarop vertelde Jezus de gelijkenis van de barmhartige Samaritaan. <em>Zie ook: schriftgeleerde, Wet.</em>", bijbelplaats: "Lucas 10:25, 29" }
];

// --- Wie is wie: Groepen en stromingen (13 termen, alfabetisch) -------------
const ONTDEK_WIE_GROEPEN = [
    { term: "Epicureeërs en stoïcijnen", uitleg: "Twee groepen Griekse filosofen die Paulus in Athene tegenkwam. Ze gingen op de markt met hem in gesprek en namen hem mee naar de Areopagus, de plek waar de stad over nieuwe ideeën vergaderde. De epicureeërs volgden de leraar Epicurus: volgens hen was het doel van het leven een rustig bestaan, zonder angst en pijn, en bemoeiden de goden zich niet met mensen. De stoïcijnen waren genoemd naar de Stoa, een zuilengang in Athene waar hun eerste leraar lesgaf. Zij leerden dat je kalm moest blijven, wat er ook gebeurde. Als je nu zegt dat iemand ergens stoïcijns onder blijft, bedoel je nog steeds dat hij heel rustig blijft. In zijn toespraak haalde Paulus zelfs een Griekse dichter aan, om bij hun eigen denken aan te sluiten.", bijbelplaats: "Handelingen 17:18, 28" },
    { term: "Farizeeën", uitleg: "Een Joodse groep die het heel serieus nam om precies volgens Gods regels te leven, tot in de kleinste details. Op zich knap, maar in de evangeliën botsen de farizeeën vaak met Jezus: volgens Hem ging het hun te veel om de regels en te weinig om de mensen daarachter. Hun naam komt van het Hebreeuwse <em>perushim</em>: \"de afgezonderden\".", bijbelplaats: "Matteüs 23:2-3 · Marcus 2:24" },
    { term: "Godvrezenden", uitleg: "Mensen die niet Joods waren, maar wel in de God van Israël geloofden. Ze kwamen naar de synagoge, baden tot God en probeerden naar Zijn geboden te leven, maar ze werden niet helemaal Joods. De Romeinse honderdman Cornelius was zo iemand, en ook Lydia, de purperverkoopster. Veel van de eerste christenen die niet Joods waren, kwamen uit deze groep: ze kenden de God van Israël al. <em>Zie ook: proselieten, heidenen.</em>", bijbelplaats: "Handelingen 10:2; 13:16; 16:14" },
    { term: "Grieksgezinden (Hellenisten)", uitleg: "Joden die Grieks spraken. Vaak waren ze opgegroeid buiten het land Israël, in steden waar iedereen Grieks sprak. Andere Joden spraken Aramees, de taal van Jezus. In de eerste gemeente in Jeruzalem klaagden de Grieksgezinden dat hun weduwen werden vergeten bij de dagelijkse uitdeling van eten. Daarom werden er zeven mannen gekozen om daarvoor te zorgen, onder wie Stefanus.", bijbelplaats: "Handelingen 6:1-5" },
    { term: "Heidenen", uitleg: "In de Bijbel: mensen die niet bij het Joodse volk hoorden en de God van Israël (nog) niet kenden — het betekent gewoon \"niet-Joden\". Het was geen scheldwoord, gewoon een aanduiding. Bijzonder is dat Jezus juist ook heidenen hielp — iets wat veel mensen toen verbaasde.", bijbelplaats: "Matteüs 8:10 · Marcus 7:26" },
    { term: "Herodianen", uitleg: "Aanhangers van de familie van koning Herodes, die met de Romeinen samenwerkte. We weten maar weinig over hen. In de evangeliën trekken ze op met de farizeeën, een opvallend tweetal, want die dachten over veel dingen heel anders. Samen probeerden ze Jezus in de val te lokken, met de vraag of je belasting aan de keizer moest betalen.", bijbelplaats: "Marcus 3:6; 12:13-14" },
    { term: "Nikolaïeten", uitleg: "Een groep in de gemeenten van Efeze en Pergamum, waarover het boek Openbaring schrijft. Jezus prijst de gemeente van Efeze omdat die niets van hun daden moest hebben. Wat de nikolaïeten precies leerden, vertelt de Bijbel niet. Openbaring noemt hen wel in één adem met mensen die meededen aan feesten ter ere van afgoden.", bijbelplaats: "Openbaring 2:6, 14-15" },
    { term: "Proselieten", uitleg: "Mensen die niet Joods geboren waren, maar helemaal Joods waren geworden. Het Griekse woord <em>prosēlytos</em> betekent \"iemand die erbij gekomen is\". Ze hielden de hele Wet van Mozes en hoorden echt bij het Joodse volk. Met Pinksteren waren er ook proselieten in Jeruzalem die de apostelen in hun eigen taal hoorden spreken. Nikolaüs uit Antiochië, een van de zeven helpers uit de eerste gemeente, was een proseliet. Het verschil met godvrezenden: die geloofden in dezelfde God, maar werden niet helemaal Joods. <em>Zie ook: godvrezenden.</em>", bijbelplaats: "Handelingen 2:10-11; 6:5" },
    { term: "Sadduceeën", uitleg: "Een groep voorname Joden, vaak priesters, rond de tempel. Hun naam komt van Sadok, de hogepriester in de tijd van koning David en koning Salomo; de belangrijkste priesterfamilies stamden van hem af. Als groep ontstonden ze zo'n honderdvijftig jaar voor de geboorte van Jezus, in dezelfde tijd als de farizeeën. De sadduceeën hielden zich aan de geschreven Wet van Mozes en wezen de uitleg en gewoonten af die de farizeeën daaraan hadden toegevoegd. Ze geloofden niet in een opstanding uit de dood — en daarin verschilden ze juist van de farizeeën. Omdat ze de tempel bestuurden, werkten ze nauw samen met de Romeinen. Toen de tempel in het jaar 70 werd verwoest, verdween ook deze groep.", bijbelplaats: "1 Koningen 2:35 · Matteüs 22:23 · Handelingen 23:8" },
    { term: "Samaritanen", uitleg: "Het volk van Samaria, het gebied tussen Galilea in het noorden en Judea in het zuiden. De Samaritanen geloofden ook in de God van Israël, maar ze vereerden Hem op hun eigen berg, de Garizim, en niet in de tempel in Jeruzalem. Van de Bijbel namen ze alleen de eerste vijf boeken aan. Joden en Samaritanen gingen daarom meestal niet met elkaar om. Juist daardoor vielen de verhalen van Jezus zo op: Hij praatte met een Samaritaanse vrouw bij een waterput, en in Zijn gelijkenis is het een Samaritaan die de gewonde man helpt. Ook nu leven er nog Samaritanen: een kleine duizend mensen.", bijbelplaats: "Johannes 4:9, 20 · Lucas 10:33" },
    { term: "Tovenaars", uitleg: "Mensen die beweerden met geheime krachten en spreuken wonderen te kunnen doen of de toekomst te kunnen zien. In Samaria maakte de tovenaar Simon veel indruk op de mensen. Toen hij zag wat de apostelen deden, wilde hij de kracht van de Heilige Geest kopen. Daarom heet het kopen van een kerkelijk ambt nu nog \"simonie\". Op Cyprus probeerde de tovenaar Elymas de Romeinse proconsul van het geloof af te houden. In het Grieks staat hier hetzelfde woord als bij de wijzen uit het oosten, maar bij hen bedoelt Matteüs geleerden die de sterren bestudeerden. <em>Zie ook: wijzen uit het oosten.</em>", bijbelplaats: "Handelingen 8:9, 18-20; 13:6-8" },
    { term: "Wijzen uit het oosten", uitleg: "Geleerden die de sterren bestudeerden. Ze kwamen uit het oosten, uit Perzië of Babylonië. Ze zagen een bijzondere ster en reisden naar Jeruzalem om de pasgeboren koning van de Joden te zoeken. Ze brachten goud, wierook en mirre mee. Matteüs noemt geen aantal, maar vanwege de drie geschenken spreekt men al heel lang van drie wijzen. Later werden ze ook koningen genoemd, omdat in de Psalmen staat dat koningen geschenken zullen brengen. In de westerse overlevering heten ze Caspar, Melchior en Balthasar. Volgens een oude beschrijving was Melchior een oude man met een lange witte baard, die goud bracht. Caspar was jong en had nog geen baard; hij bracht wierook. Balthasar had een donkere huid en een volle baard, en bracht mirre. Waar ieder vandaan kwam, vertellen de oude verhalen verschillend. Vaak hoor je dat Melchior uit Perzië kwam, Caspar uit India en Balthasar uit Arabië, maar andere verhalen noemen weer andere landen. Later zag men in hen de drie werelddelen die men toen kende, Europa, Azië en Afrika: zo kwamen alle volken het kind eren. In veel kerken wordt hun bezoek gevierd op Driekoningen, op 6 januari.", bijbelplaats: "Matteüs 2:1-11 · Psalm 72:10" },
    { term: "Zeloten (ijveraars)", uitleg: "Het woord zeloot betekent \"ijveraar\": iemand die zich met hart en ziel voor iets inzet. Zeloten waren Joden die vonden dat Israël alleen God als koning mocht hebben en dat de Romeinen weg moesten, desnoods met geweld. Toen Jezus nog een kind was, kwam Judas uit Galilea al met zo'n groep in opstand tegen de Romeinen. Een van de twaalf apostelen was zo'n ijveraar: Simon de Zeloot. In Matteüs en Marcus heet hij Simon de Kananeeër; dat is hetzelfde woord in het Aramees, en het heeft niets met het land Kanaän te maken. Opvallend is dat Jezus in dezelfde groep van twaalf ook Matteüs koos, een tollenaar die juist voor de Romeinen werkte.", bijbelplaats: "Matteüs 10:4 · Lucas 6:15 · Handelingen 1:13; 5:37" }
];

// --- Wie is wie: Bestuur en rechtspraak (11 termen, alfabetisch) -------------
const ONTDEK_WIE_BESTUUR = [
    { term: "Aziarchen (bestuurders van Asia)", uitleg: "Belangrijke en rijke mannen uit de provincie Asia. Ze organiseerden grote feesten en spelen, ook ter ere van de keizer. Asia was toen de naam van een Romeinse provincie in het westen van het huidige Turkije, met Efeze als belangrijkste stad, en niet het werelddeel Azië. Tijdens het oproer in Efeze lieten enkele Aziarchen Paulus weten dat hij niet naar het theater moest gaan. Ze waren vrienden van hem: Paulus had dus ook vrienden op hoge posten.", bijbelplaats: "Handelingen 19:31" },
    { term: "Gerechtsdienaar", uitleg: "Een dienaar van de rechtbank, die uitvoerde wat de rechter besliste, bijvoorbeeld iemand naar de gevangenis brengen. Jezus noemt hem in de Bergrede: maak het op tijd goed met je tegenstander, anders kom je bij de rechter en de gerechtsdienaar terecht. In Filippi, een stad die als een stukje Rome werd bestuurd, liepen de gerechtsdienaars met een bundel staven als teken van hun gezag. Zij kwamen melden dat Paulus en Silas vrij waren. Maar Paulus liet weten dat ze Romeinse burgers waren, en dat de bestuurders hen dan zelf maar moesten komen halen.", bijbelplaats: "Matteüs 5:25 · Handelingen 16:35-39" },
    { term: "Keizer", uitleg: "De hoogste heerser van het Romeinse Rijk. Het woord komt van Caesar, de familienaam van Julius Caesar; de keizers na hem namen die naam aan als titel. In het Latijn sprak je Caesar uit als \"kaisar\", en daar komt ons woord keizer vandaan. Drie keizers worden in het Nieuwe Testament bij naam genoemd: Augustus, die de volkstelling liet houden toen Jezus werd geboren; Tiberius, in wiens tijd Johannes de Doper begon te preken; en Claudius, die de Joden uit Rome liet vertrekken. Jezus zei dat je de keizer moest geven wat van de keizer is, en God wat van God is. En toen Paulus zei dat hij zich op de keizer beriep, was dat keizer Nero.", bijbelplaats: "Lucas 2:1; 3:1 · Marcus 12:17 · Handelingen 18:2; 25:11" },
    { term: "Koning (onder Rome)", uitleg: "In de tijd van het Nieuwe Testament was een koning in het land Israël geen vrije vorst. Hij regeerde omdat Rome dat toestond, en Rome kon hem ook weer afzetten. Herodes de Grote kreeg van de Romeinen de titel \"koning van de Joden\". Hij liet de tempel in Jeruzalem prachtig verbouwen. Toen de wijzen uit het oosten naar de pasgeboren koning van de Joden vroegen, schrok hij dan ook: die titel was van hem. Later werden ook zijn kleinzoon Herodes Agrippa en diens zoon Agrippa koning. Voor die laatste hield Paulus in Caesarea een verdediging. Omdat de Bijbel verschillende van hen gewoon Herodes noemt, is het soms puzzelen wie wie is. Een overzicht van alle heersers uit deze familie staat bij De familie Herodes. <em>Zie ook: tetrarch.</em>", bijbelplaats: "Matteüs 2:1-3 · Handelingen 12:1; 25:13" },
    { term: "Pleitbezorger (advocaat)", uitleg: "Iemand die voor een ander het woord doet bij een rechter, zoals een advocaat nu. Toen Paulus voor de stadhouder Felix terechtstond, nam de hogepriester Ananias een pleitbezorger mee: Tertullus. Die begon met veel mooie woorden over Felix, en beschuldigde Paulus daarna van onrust stoken. Sommige vertalingen noemen Tertullus een redenaar. In de eerste brief van Johannes wordt Jezus zelf onze pleitbezorger bij de Vader genoemd: iemand die voor ons opkomt. Andere vertalingen zeggen daar \"voorspraak\".", bijbelplaats: "Handelingen 24:1-5 · 1 Johannes 2:1" },
    { term: "Proconsul", uitleg: "De bestuurder van een rustige Romeinse provincie, aangesteld door de Romeinse senaat. In onrustige gebieden, zoals Judea, benoemde de keizer zelf een bestuurder, met soldaten erbij. Paulus ontmoette twee proconsuls. Op Cyprus was dat Sergius Paulus, die tot geloof kwam. In Achaje, het zuiden van Griekenland, was dat Gallio, de broer van de beroemde filosoof Seneca. Toen de Joden van Korinte Paulus bij hem aanklaagden, wilde Gallio er niets mee te maken hebben. In Delfi is een steen gevonden met zijn naam erop; daardoor weten we vrij precies wanneer Paulus in Korinte was. <em>Zie ook: stadhouder.</em>", bijbelplaats: "Handelingen 13:7, 12; 18:12-17" },
    { term: "Stadhouder (landvoogd)", uitleg: "Een bestuurder die namens de Romeinse keizer de baas was over een gebied. Pontius Pilatus was de stadhouder over Judea. Na hem worden ook Felix en Festus genoemd; voor hen stond Paulus terecht in Caesarea. Het woord kennen we ook uit onze eigen geschiedenis: Willem van Oranje was stadhouder, namens de koning van Spanje.", bijbelplaats: "Matteüs 27:2 · Handelingen 23:24; 24:27" },
    { term: "Stadsbestuurders (politarchen)", uitleg: "In Tessalonica heetten de bestuurders van de stad politarchen. Het woord komt van <em>polis</em>, stad, en <em>archōn</em>, leider. Van <em>polis</em> komen ook onze woorden politiek en politie. Toen er onrust ontstond over Paulus en Silas, sleepte een woedende menigte hun gastheer Jason voor deze stadsbestuurders. Die lieten Jason pas gaan nadat hij borg had betaald. Het woord politarch staat nergens anders in de Bijbel en komt in oude boeken bijna niet voor, maar op oude stenen in de stad zelf is het vaak gevonden. Lucas gebruikte dus precies het woord dat ze daar zelf gebruikten.", bijbelplaats: "Handelingen 17:6-9" },
    { term: "Stadssecretaris (stadsschrijver)", uitleg: "De hoogste ambtenaar van een Griekse stad. Hij hield de besluiten en verslagen bij en leidde de volksvergadering. In Efeze brak een groot oproer uit tegen Paulus: de zilversmeden waren bang dat ze minder beeldjes van de godin Artemis zouden verkopen. De hele stad stroomde naar het theater. Daar bracht de stadssecretaris de menigte tot rust: wie een klacht had, moest die maar naar de rechter brengen. Dat theater staat er nog steeds; er pasten zo'n vijfentwintigduizend mensen in.", bijbelplaats: "Handelingen 19:35-41" },
    { term: "Stadsthesaurier (stadsrentmeester)", uitleg: "De man die het geld van een stad beheerde. In zijn brief aan de Romeinen laat Paulus de groeten doen van Erastus, de stadsthesaurier van Korinte.", bijbelplaats: "Romeinen 16:23" },
    { term: "Tetrarch (viervorst)", uitleg: "Een vorst die over een deel van een land regeert. Het woord betekent letterlijk \"heerser over een vierde deel\". Het rijk van koning Herodes de Grote werd verdeeld onder zijn zonen, en de Romeinen gaven twee van hen de titel tetrarch en niet die van koning. Herodes Antipas werd zo tetrarch van Galilea, het gebied waar Jezus opgroeide en de meeste tijd rondtrok. Een overzicht van alle heersers uit deze familie staat bij De familie Herodes.", bijbelplaats: "Lucas 3:1" }
];

// --- Wie is wie: Leger en bewaking (6 termen, alfabetisch) -------------------
const ONTDEK_WIE_LEGER = [
    { term: "Cohort (afdeling)", uitleg: "Een afdeling van het Romeinse leger van zo'n vijfhonderd soldaten; tien cohorten samen vormden een legioen. Een cohort stond onder leiding van een overste, en daaronder had elke honderdman zijn eigen groep. De honderdman Cornelius hoorde bij de Italiaanse afdeling. De honderdman Julius, die Paulus naar Rome bracht, hoorde bij de keizerlijke afdeling. Oudere vertalingen zeggen hier soms \"bende\", maar dat betekent gewoon een groep soldaten.", bijbelplaats: "Handelingen 10:1; 27:1" },
    { term: "Gevangenbewaarder (cipier)", uitleg: "Iemand die de gevangenen bewaakte. Als er een ontsnapte, kon hij daar zelf zwaar voor gestraft worden. In Filippi zaten Paulus en Silas midden in de nacht in de gevangenis God te loven met liederen. Toen kwam er een aardbeving, en alle deuren sprongen open. De gevangenbewaarder schrok vreselijk, want hij dacht dat iedereen gevlucht was. Maar Paulus riep dat ze er allemaal nog waren. Die nacht kwam de gevangenbewaarder met zijn hele huis tot geloof. Hij waste de wonden van Paulus en Silas en gaf hun te eten.", bijbelplaats: "Handelingen 16:23-34" },
    { term: "Honderdman (centurio)", uitleg: "Een Romeinse officier met een eigen groep soldaten. Het woord zegt het al: in het begin waren dat er honderd, later meestal tachtig. In het Latijn heette hij centurio, van <em>centum</em>, honderd. Opvallend is hoe vaak honderdmannen in het Nieuwe Testament er goed afkomen. In Kafarnaüm vroeg een honderdman Jezus om zijn zieke knecht te genezen, en Jezus zei dat Hij in Israël bij niemand zo'n groot geloof had gevonden. Cornelius werd met zijn hele huis gedoopt door Petrus. En de honderdman Julius, die Paulus naar Rome bracht, beschermde hem toen het schip verging.", bijbelplaats: "Matteüs 8:5-10 · Handelingen 10:1, 48; 27:1, 43" },
    { term: "Legioen", uitleg: "De grootste afdeling van het Romeinse leger: zo'n vijfduizend soldaten. Daarom werd het woord ook gebruikt voor een enorm aantal. Toen Jezus een man bevrijdde die bezeten was door boze geesten, vroeg Hij hoe hij heette. \"Legioen,\" zei de man, \"want we zijn met velen.\" En toen Jezus gevangen werd genomen, zei Hij tegen Petrus dat Zijn Vader Hem meer dan twaalf legioenen engelen zou kunnen sturen.", bijbelplaats: "Matteüs 26:53 · Marcus 5:9" },
    { term: "Overste (tribuun)", uitleg: "Een hoge Romeinse officier, de baas van een cohort. In het Grieks heet hij letterlijk \"aanvoerder van duizend\". In Jeruzalem woonde de overste Claudius Lysias met zijn soldaten in de burcht Antonia, vlak naast de tempel. Toen een woedende menigte Paulus in de tempel aanviel, rende hij met zijn soldaten naar beneden en haalde Paulus weg. Later hoorde hij dat Paulus Romeins burger was. Hij vertelde dat hij zelf veel geld voor dat burgerrecht had betaald, maar Paulus had het al van geboorte. Toen een neef van Paulus een geheim plan tegen hem ontdekte, liet de overste Paulus 's nachts met honderden soldaten en ruiters naar de stadhouder in Caesarea brengen.", bijbelplaats: "Handelingen 21:31-33; 22:28; 23:16-26" },
    { term: "Pretorium", uitleg: "Eerst was het pretorium de tent van een Romeinse veldheer. Later heette zo ook het paleis waar een Romeinse bestuurder woonde en recht sprak, en de soldaten die daar de wacht hielden. In het pretorium van Pilatus in Jeruzalem werd Jezus door de soldaten bespot. In Caesarea werd Paulus bewaakt in het pretorium van Herodes. En vanuit de gevangenis schreef Paulus aan de gemeente in Filippi dat het hele pretorium wist dat hij gevangen zat omdat hij Christus volgde. Sommige vertalingen zeggen daar \"de keizerlijke garde\".", bijbelplaats: "Matteüs 27:27 · Handelingen 23:35 · Filippenzen 1:13" }
];

// --- Wie is wie: Taken in de eerste gemeenten (8 termen, alfabetisch) --------
const ONTDEK_WIE_GEMEENTEN = [
    { term: "Apostel", uitleg: "Het woord betekent \"gezant\" of \"boodschapper\", van het Griekse <em>apostolos</em>: iemand die wordt uitgezonden. In de oudheid was een apostel geen gewone postbode, maar een officiële afgezant — zoals een ambassadeur — die namens een koning op pad ging; zijn woorden golden als de woorden van de koning zelf. In het Nieuwe Testament koos Jezus twaalf van Zijn leerlingen (discipelen) uit en zond hen uit om Zijn boodschap te verspreiden en zieken te genezen; vanaf dat moment waren zij Zijn apostelen. In de eerste kerk werd de eis zelfs strenger: een echte apostel moest Jezus tijdens Zijn leven hebben meegemaakt én Hem na Zijn dood weer levend hebben gezien. Eén beroemde uitzondering is Paulus: hij had de levende Jezus nooit ontmoet, maar noemde zich tóch apostel, omdat de opgestane Jezus hém op weg naar Damascus persoonlijk had uitgekozen en uitgezonden.", bijbelplaats: "Marcus 3:14 · Handelingen 1:21-22 · 1 Korintiërs 15:8-9" },
    { term: "Diaken", uitleg: "Het Griekse woord <em>diakonos</em> betekent \"dienaar\". Paulus groet in zijn brief aan de Filippenzen de opzieners en de diakenen, en aan Timoteüs schrijft hij waar een goede diaken aan moet voldoen. Ook Febe wordt genoemd: zij diende de gemeente van Kenchreeën, de havenstad van Korinte. Sommige vertalingen noemen haar dienares, andere diaken. Handelingen vertelt over zeven mannen die werden gekozen om te zorgen voor de dagelijkse uitdeling van eten, zodat de apostelen tijd hielden voor gebed en verkondiging. Het woord diaken staat daar niet, maar veel kerken zien in hen de eerste diakenen. Ook nu kennen de kerken diakenen. In de Katholieke Kerk is een diaken gewijd en mag hij onder meer dopen, preken en een huwelijk inzegenen; ook de orthodoxe kerken hebben gewijde diakenen, die helpen bij de viering. In protestantse kerken en veel evangelische gemeenten zorgen diakenen vooral voor mensen die hulp nodig hebben, en zij halen de collecte op.", bijbelplaats: "Handelingen 6:1-6 · Romeinen 16:1 · Filippenzen 1:1 · 1 Timoteüs 3:8" },
    { term: "Discipel (leerling)", uitleg: "Een leerling van Jezus die met Hem meetrok en van Hem leerde. \"Discipel\" en \"leerling\" betekenen hetzelfde. Jezus had veel discipelen; uit die grote groep koos Hij een kleinere groep apostelen die Hij eropuit stuurde.", bijbelplaats: "Lucas 6:13" },
    { term: "Evangelist", uitleg: "Iemand die het evangelie, het goede nieuws over Jezus, aan anderen vertelt en daarvoor vaak rondreist. Het Griekse <em>euangelion</em> betekent \"goed nieuws\": <em>eu</em> is goed, en een <em>angelos</em> is een bode. Van dat laatste woord komt ook ons woord engel: een bode van God. Paulus noemt evangelisten naast apostelen, profeten, herders en leraars. De bekendste evangelist in Handelingen is Filippus, een van de zeven helpers uit de eerste gemeente. Hij vertelde in Samaria over Jezus en doopte onderweg een kamerheer uit Ethiopië. Let op: dat is een andere Filippus dan de apostel. Later zijn ook Matteüs, Marcus, Lucas en Johannes de vier evangelisten gaan heten, naar de vier evangeliën die hun namen dragen. <em>Zie ook: evangelie.</em>", bijbelplaats: "Handelingen 8:5, 38; 21:8 · Efeziërs 4:11" },
    { term: "Herder (in de gemeente)", uitleg: "In de Bijbel is de herder een beeld voor iemand die voor anderen zorgt, zoals een herder voor zijn schapen. Jezus noemt zichzelf de goede Herder, die Zijn leven geeft voor de schapen. Paulus noemt herders als een taak in de gemeente, en Petrus vraagt de oudsten om goed te zorgen voor de kudde van God. Het Latijnse woord voor herder is <em>pastor</em>. Daar komen onze woorden pastoor en pastor vandaan: de pastoor van een parochie en de pastor van een gemeente heten dus eigenlijk herder.", bijbelplaats: "Johannes 10:11 · Efeziërs 4:11 · 1 Petrus 5:2" },
    { term: "Opziener", uitleg: "Iemand die toezicht houdt; van het Griekse <em>episkopos</em>. Via het Latijn is daar later ons woord \"bisschop\" uit ontstaan. In de brieven van Paulus gaat het om iemand die leiding gaf aan een plaatselijke gemeente of kerk. Hoe die taak er nu uitziet, verschilt per kerk. In de Katholieke Kerk is de bisschop de leider van een bisdom: een gebied met veel parochies. Katholieken zien de bisschoppen als opvolgers van de apostelen. In veel protestantse kerken houden ouderlingen toezicht op de gemeente. <em>Zie ook: bisschop, gemeente, kerk.</em>", bijbelplaats: "Filippenzen 1:1 · 1 Timoteüs 3:1-2" },
    { term: "Oudste (ouderling)", uitleg: "Een ervaren gelovige die samen met anderen leiding geeft aan een gemeente. Het woord betekent eigenlijk \"oudere\", van het Griekse <em>presbyteros</em>. Paulus vraagt Titus om in elke stad zulke oudsten aan te stellen. In veel protestantse kerken houden ouderlingen nog steeds toezicht op de gemeente en zorgen ze voor de mensen die erbij horen. Ook veel evangelische gemeenten en pinkstergemeenten worden geleid door oudsten. <em>Zie ook: opziener, bisschop.</em>", bijbelplaats: "Handelingen 14:23 · Titus 1:5" },
    { term: "Profeet", uitleg: "Iemand die namens God spreekt. Geen waarzegger met een glazen bol: een profeet voorspelt niet zomaar wat er gaat gebeuren, maar roept de mensen vooral op om naar God te luisteren — ook als ze dat liever niet horen. Een waarschuwing is meestal een laatste kans om het anders te doen. Toen de profeet Jona aankondigde dat de stad Nineve zou vergaan, kregen de inwoners spijt en veranderden ze hun leven — en toen liet God het onheil niet doorgaan. Dat laat zien dat God het aangekondigde onheil eigenlijk niet wíl: liever ziet Hij dat mensen veranderen. (Jona baalde daar trouwens flink van.) Ook in het Nieuwe Testament zijn er profeten: de oude Anna in de tempel, Agabus, die een hongersnood voorzei, en de vier dochters van Filippus. Paulus noemt profeteren een gave van de Heilige Geest, die de gemeente opbouwt en bemoedigt. In pinkstergemeenten en veel evangelische gemeenten heeft die gave weer een belangrijke plek.", bijbelplaats: "Jona 3:4-10 · Lucas 2:36 · Handelingen 11:27-28; 21:9 · 1 Korintiërs 14:3" }
];

// --- Wie is wie: Beroepen en werk (14 termen, alfabetisch) -------------------
const ONTDEK_WIE_BEROEPEN = [
    { term: "Bouwmeester", uitleg: "Iemand die een bouwwerk ontwerpt en de leiding heeft over het bouwen. Het Griekse woord is <em>architektōn</em>, en daar komt ons woord architect vandaan. Paulus vergelijkt zichzelf met een wijze bouwmeester: hij legde in Korinte het fundament van de gemeente, en dat fundament is Jezus Christus. Anderen bouwden daarop verder. In de brief aan de Hebreeën wordt God zelf de bouwmeester genoemd van de stad waar Abraham naar uitkeek.", bijbelplaats: "1 Korintiërs 3:10-11 · Hebreeën 11:10" },
    { term: "Dagloner", uitleg: "Een arbeider zonder vaste baan. Hij stond 's ochtends op het marktplein te wachten tot iemand hem voor één dag inhuurde, en kreeg 's avonds zijn loon: één denarie, het gewone loon voor een dag werken. In de Wet van Mozes stond dat je een dagloner zijn loon nog dezelfde dag moest geven, want hij had het nodig om te eten. In de gelijkenis van de arbeiders in de wijngaard krijgen alle dagloners hetzelfde loon, ook wie pas aan het eind van de dag begon.", bijbelplaats: "Deuteronomium 24:14-15 · Matteüs 20:1-16" },
    { term: "Herbergier", uitleg: "De eigenaar van een herberg: een eenvoudig logement langs de weg, waar reizigers konden overnachten, soms samen met hun dieren. In de gelijkenis van de barmhartige Samaritaan brengt de Samaritaan de gewonde man naar een herberg. Hij geeft de herbergier twee denaries en belooft dat hij op de terugweg betaalt als het meer kost.", bijbelplaats: "Lucas 10:34-35" },
    { term: "Leerlooier", uitleg: "Iemand die van dierenhuiden leer maakte. Het was vies en stinkend werk, en omdat een leerlooier steeds met dode dieren bezig was, keken veel Joden op hem neer. Daarom woonde hij vaak aan de rand van de stad. In Joppe logeerde Petrus bij Simon de leerlooier, in een huis aan zee. Dat een apostel daar bleef, was al bijzonder. En juist op het dak van dat huis kreeg Petrus het visioen waarin God hem leerde dat hij niemand onrein mocht noemen.", bijbelplaats: "Handelingen 9:43; 10:6, 9-16, 28" },
    { term: "Pachter", uitleg: "Iemand die een stuk land of een wijngaard huurde van de eigenaar. Hij bewerkte het land zelf, en als huur gaf hij de eigenaar een deel van de oogst. Jezus vertelde een gelijkenis over pachters die de eigenaar zijn deel niet wilden geven: de knechten die het kwamen ophalen, sloegen ze en stuurden ze met lege handen weg. Daarmee liet Hij zien hoe de leiders van het volk omgingen met de boodschappers van God.", bijbelplaats: "Marcus 12:1-12" },
    { term: "Pottenbakker", uitleg: "Iemand die van klei potten, kruiken en schalen maakte, op een draaiende schijf. Zolang de klei nog nat is, kan de pottenbakker hem opnieuw vormen als er iets misgaat. De profeet Jeremia keek in de werkplaats van een pottenbakker en hoorde God zeggen: zoals klei in de hand van de pottenbakker, zo zijn jullie in Mijn hand. Paulus gebruikt hetzelfde beeld in zijn brief aan de Romeinen.", bijbelplaats: "Jeremia 18:1-6 · Romeinen 9:21" },
    { term: "Purperverkoopster", uitleg: "Een vrouw die handelde in purperen stof. Purper is een diepe kleur tussen rood en paars in, ongeveer zo: <span class=\"naslag-kleurvlak\" style=\"background:#66023C\" role=\"img\" aria-label=\"purper\"></span> Echte purperverf werd gemaakt van zeeslakken; voor een beetje verf had je duizenden slakken nodig. Daarom was purperen stof heel duur, en droegen vooral koningen en rijke mensen het, zoals de rijke man in een gelijkenis van Jezus. In Filippi ontmoette Paulus Lydia, een purperverkoopster uit de stad Tyatira. Ze vereerde God al, en toen ze Paulus hoorde, kwam ze met haar hele huis tot geloof. Daarna nodigde ze Paulus en zijn reisgenoten uit om bij haar te logeren.", bijbelplaats: "Lucas 16:19 · Handelingen 16:14-15" },
    { term: "Stuurman en scheepseigenaar", uitleg: "De stuurman bestuurde het schip, de scheepseigenaar was de baas ervan. Toen Paulus als gevangene naar Rome werd gebracht, waarschuwde hij dat het te gevaarlijk was om nog verder te varen. Maar de honderdman luisterde liever naar de stuurman en de scheepseigenaar. Het schip kwam in een zware storm terecht en liep vast bij Malta; toch kwam iedereen er levend vanaf, zoals Paulus had gezegd. Jakobus schrijft dat een klein roer een groot schip de kant op stuurt die de stuurman wil. Zo stuurt ook onze kleine tong ons hele leven.", bijbelplaats: "Handelingen 27:10-11, 41-44 · Jakobus 3:4-5" },
    { term: "Tentenmaker", uitleg: "Iemand die tenten maakte, van leer of van stof van geitenhaar. Paulus had dat vak geleerd, net als het echtpaar Aquila en Priscilla, bij wie hij in Korinte woonde en werkte. Zo verdiende Paulus zijn eigen brood en hoefde hij de gemeenten niet tot last te zijn. Een tent was toen heel gewoon: reizigers, herders en soldaten sliepen erin.", bijbelplaats: "Handelingen 18:2-3; 20:34 · 1 Tessalonicenzen 2:9" },
    { term: "Timmerman", uitleg: "In het Grieks staat hier <em>tektōn</em>: een vakman die bouwt, met hout, maar ook met steen. Dat is dus een breder vak dan een timmerman nu: eerder een bouwvakker en meubelmaker tegelijk. Hij maakte deuren, dakbalken, meubels en landbouwgereedschap zoals ploegen en jukken. Jozef was zo'n vakman, en Jezus leerde het vak van hem. De mensen in Nazaret zeiden daarom verbaasd: is dat niet de timmerman, de zoon van Maria?", bijbelplaats: "Matteüs 13:55 · Marcus 6:3" },
    { term: "Tollenaar", uitleg: "Een belastingontvanger die tol en belasting ophaalde voor de Romeinen, of in Galilea voor Herodes Antipas, die met Rome samenwerkte. Veel mensen zagen hem als een verrader, en hij rekende vaak stiekem een beetje te veel — handig voor zijn eigen portemonnee. Zacheüs in Jericho was zelfs een oppertollenaar, de baas van andere tollenaars. Toch koos Jezus er één als leerling uit: Matteüs, die later zelfs een evangelie schreef.", bijbelplaats: "Matteüs 9:9 · Lucas 3:12-13; 19:2" },
    { term: "Volder", uitleg: "Iemand die wol en stof schoonmaakte en bleekte. Hij waste de stof, stampte erop en maakte hem met speciale middelen zo wit mogelijk. Toen Jezus op de berg van gedaante veranderde, werden Zijn kleren zo stralend wit als geen volder op aarde ze kon maken.", bijbelplaats: "Marcus 9:3" },
    { term: "Wijngaardenier (wijnbouwer)", uitleg: "Iemand die een wijngaard verzorgt: hij snoeit de wijnstokken, bindt ze op en oogst de druiven. Jezus zei: Ik ben de ware wijnstok, en Mijn Vader is de wijngaardenier. Hij snoeit de ranken, zodat ze meer vrucht dragen. In een andere gelijkenis vraagt een wijngaardenier de eigenaar om een vijgenboom die geen vruchten draagt nog één jaar de tijd te geven.", bijbelplaats: "Johannes 15:1-2 · Lucas 13:6-9" },
    { term: "Zilversmid", uitleg: "Iemand die voorwerpen van zilver maakte. In Efeze stond de beroemde tempel van de godin Artemis, een van de zeven wereldwonderen. De zilversmid Demetrius verdiende goed aan zilveren tempeltjes van Artemis, die pelgrims kochten. Toen door Paulus veel mensen niet meer in afgoden geloofden, was hij bang dat zijn handel zou verdwijnen. Hij riep de andere ambachtslieden bij elkaar, en zo brak er een groot oproer uit in de stad.", bijbelplaats: "Handelingen 19:23-29" }
];

// --- Wie is wie: Huishouden en dienst (7 termen, alfabetisch) ----------------
const ONTDEK_WIE_HUISHOUDEN = [
    { term: "Deurwachter (portier)", uitleg: "Iemand die bij de deur of poort van een huis of binnenplaats de wacht hield en besliste wie er binnen mocht. In rijke huizen deed vaak een slaaf of slavin dat werk. Toen Jezus gevangen was genomen, vroeg de deurwachteres van de hogepriester aan Petrus of hij ook een van Zijn leerlingen was, en Petrus zei van niet. Veel vrolijker is het verhaal van Rhode. Toen Petrus uit de gevangenis was bevrijd en 's nachts aanklopte, was zij zo blij dat ze vergat de deur open te doen en eerst naar binnen rende om het te vertellen.", bijbelplaats: "Johannes 18:16-17 · Handelingen 12:13-16" },
    { term: "Kamerheer (hoveling)", uitleg: "Een hoge dienaar aan het hof van een koning of koningin. De bekendste in de Bijbel is de kamerheer uit Ethiopië, die de hele schatkist van de koningin beheerde. Ethiopië was toen het rijk ten zuiden van Egypte, ongeveer waar nu Soedan ligt, en Kandake was geen naam maar de titel van de koningin. Op de terugweg uit Jeruzalem las hij in zijn wagen uit de profeet Jesaja. Filippus legde hem uit dat het over Jezus ging, en nog onderweg liet de kamerheer zich dopen. Sommige vertalingen noemen hem een eunuch: een man die aan een vorstenhof diende en geen eigen gezin kon hebben. Ook koning Herodes Agrippa had een kamerheer, Blastus.", bijbelplaats: "Handelingen 8:26-39; 12:20" },
    { term: "Rentmeester", uitleg: "Iemand die namens de eigenaar een huis of landgoed beheerde: hij regelde het geld, de voorraden en het werk van de knechten. Het Griekse woord is <em>oikonomos</em>, \"die het huis regelt\", en daar komt ons woord economie vandaan. Jezus vertelde over een oneerlijke rentmeester die ontslagen zou worden en snel de schulden van anderen verlaagde, zodat ze later voor hem zouden zorgen. De eigenaar prees niet zijn oneerlijkheid, maar wel dat hij slim vooruitdacht. Paulus noemt zichzelf en de andere apostelen rentmeesters van Gods geheimen, en schrijft dat een rentmeester vooral betrouwbaar moet zijn.", bijbelplaats: "Lucas 16:1-8 · 1 Korintiërs 4:1-2" },
    { term: "Schuldeiser", uitleg: "Iemand die geld heeft uitgeleend en het terug wil hebben; wie het geld leende, heet de schuldenaar. Wie zijn schuld niet kon betalen, kwam in grote problemen: hij kon in de gevangenis belanden of zelfs als slaaf worden verkocht. Jezus vertelde over een schuldeiser die twee mensen hun schuld kwijtschold, de een vijfhonderd denaries en de ander vijftig, en vroeg wie van de twee hem het meest zou liefhebben. In het Onzevader bidden we dat God ons onze schuld vergeeft, zoals wij anderen hun schuld vergeven.", bijbelplaats: "Matteüs 6:12; 18:25 · Lucas 7:41-43" },
    { term: "Slaaf (knecht)", uitleg: "In het Romeinse Rijk waren heel veel mensen slaaf: ze hoorden bij een eigenaar en moesten voor hem werken. Je kon slaaf worden doordat je als krijgsgevangene werd verkocht, doordat je je schulden niet kon betalen, of doordat je ouders al slaaf waren. Sommige slaven deden zwaar werk, andere hadden belangrijke taken, als rentmeester, leraar of arts. Het Griekse woord <em>doulos</em> wordt in de ene vertaling met slaaf vertaald, in de andere met knecht of dienaar. Paulus schreef een brief aan Filemon over diens weggelopen slaaf Onesimus, die christen was geworden. Hij vroeg Filemon om Onesimus terug te ontvangen als een geliefde broer. Want, schreef Paulus, in Christus zijn slaaf en vrije één.", bijbelplaats: "Galaten 3:28 · Filemon 10-16" },
    { term: "Tuchtmeester (opvoeder)", uitleg: "In rijke Griekse en Romeinse gezinnen had een jongen een eigen begeleider, vaak een slaaf. Die bracht hem naar school, lette erop dat hij zich goed gedroeg en hield hem streng in de gaten tot hij volwassen was. Hij was dus niet de leraar, maar de bewaker onderweg. Het Griekse woord is <em>paidagōgos</em>, \"kindergeleider\", en daar komt ons woord pedagoog vandaan. Paulus schrijft dat de Wet van Mozes zo'n tuchtmeester was, tot Christus kwam.", bijbelplaats: "Galaten 3:24-25 · 1 Korintiërs 4:15" },
    { term: "Voogden en beheerders", uitleg: "Een rijke vader kon bepalen dat zijn zoon pas vanaf een bepaalde leeftijd zelf over zijn erfenis mocht beslissen. Tot die tijd zorgde een voogd voor het kind, en een beheerder voor het geld en de bezittingen. Paulus gebruikt dat beeld in zijn brief aan de Galaten: zolang de erfgenaam klein is, verschilt hij nauwelijks van een slaaf, ook al is alles van hem. Zo waren de mensen vóór Christus, schrijft Paulus; door Hem zijn ze kinderen van God geworden.", bijbelplaats: "Galaten 4:1-7" }
];

// --- Wie is wie: De familie Herodes (artikel met tabel) ----------------------
const ONTDEK_WIE_HERODES = [
    { kader: "In het Nieuwe Testament kom je zes heersers uit één familie tegen: de familie van koning Herodes. Ze regeerden allemaal omdat de Romeinen dat toestonden. Hier zie je wie wie was, en wanneer." },
    { item: "Herodes de Grote was koning over het hele land toen Jezus werd geboren. De Romeinen hadden hem die titel gegeven. Hij liet de tempel in Jeruzalem prachtig verbouwen, en bij hem kwamen de wijzen uit het oosten op bezoek." },
    { item: "Na zijn dood verdeelden de Romeinen zijn rijk onder drie van zijn zonen. Archelaüs kreeg Judea en Samaria, Herodes Antipas kreeg Galilea en het gebied aan de overkant van de Jordaan, en Filippus kreeg de gebieden ten noordoosten van het meer van Galilea. Jozef was bang voor Archelaüs en ging daarom met Maria en Jezus in Galilea wonen. Archelaüs regeerde zo slecht dat de Romeinen hem na tien jaar afzetten. Vanaf toen bestuurden de Romeinen Judea zelf: de keizer stuurde er steeds een Romeinse stadhouder heen, die na een aantal jaren door een volgende werd opgevolgd. De bekendste van hen is Pontius Pilatus, die er van het jaar 26 tot 36 was, in de tijd dat Jezus rondtrok." },
    { item: "Zo had Jezus met twee heersers te maken. In Galilea, waar Hij opgroeide, regeerde Herodes Antipas; in Jeruzalem had de Romeinse stadhouder Pilatus het voor het zeggen. Bij Zijn proces stuurde Pilatus Hem daarom ook even naar Herodes." },
    { item: "In de tijd van de apostelen werd een kleinzoon van Herodes de Grote, Herodes Agrippa, nog één keer koning over het hele land. Zijn zoon Agrippa werd later koning over gebieden in het noorden. Voor hem verdedigde Paulus zich in Caesarea." },
    { tabel: {
        koppen: ["Wanneer", "Wie", "Titel en gebied", "In de Bijbel"],
        rijen: [
            ["tot 4 v.Chr.", "Herodes de Grote", "koning over het hele land", "Matteüs 2:1"],
            ["4 v.Chr. – 6 n.Chr.", "Archelaüs", "etnarch van Judea en Samaria", "Matteüs 2:22"],
            ["4 v.Chr. – 39 n.Chr.", "Herodes Antipas", "tetrarch van Galilea", "Lucas 3:1; 23:7"],
            ["4 v.Chr. – 34 n.Chr.", "Filippus", "tetrarch in het noordoosten", "Lucas 3:1"],
            ["vanaf 6 n.Chr.", "Romeinse stadhouders, onder wie Pontius Pilatus (26 – 36)", "bestuurders van Judea", "Matteüs 27:2"],
            ["41 – 44 n.Chr.", "Herodes Agrippa", "weer koning over het hele land", "Handelingen 12:1"],
            ["vanaf ongeveer 50 n.Chr.", "Agrippa, zijn zoon", "koning in het noorden", "Handelingen 25:13"]
        ]
    } },
    { noot: "Drie van hen heten in de Bijbel gewoon Herodes. Kijk dus bij elk verhaal goed welke Herodes er bedoeld wordt." }
];

// --- Hoe leefden ze toen ----------------------------------------------------
// Het kadertje dat vroeger boven het hele Maten-scherm stond; nu één keer,
// als inleiding boven de drie onderwerpen.
const ONTDEK_HOE_INLEIDING = "Sommige maten kennen we vrij precies, andere niet — dan zeggen we dat er eerlijk bij. En oud geld omrekenen naar euro's van nu is eigenlijk niet te doen, want toen was alles anders. Daarom rekenen we vaak in \"daglonen\": wat een gewone arbeider op één dag verdiende.";

const ONTDEK_GELD = [
    { kop: "Geld in de Bijbel" },
    { noot: "Reken je dit heel ruw om naar Nederland in 2026, met een flinke marge, dan kom je ongeveer op de bedragen hieronder — uitgaand van een dagloon van zo'n 150 à 200 euro. Exacte bedragen zijn het niet, maar ze geven je wel een idee." },
    { item: "<span class=\"naslag-term\">Romeins geld</span> — het geld van de keizer" },
    { item: "<span class=\"naslag-term\">Denarie</span> — € 150 à 200, het loon voor één hele dag werken. Naar zilver: ongeveer € 7. Een zilveren muntje van vier gram met het hoofd van de keizer erop. Jezus vroeg om zo'n munt toen Hem gevraagd werd of je belasting moest betalen (Matteüs 22:19). In de gelijkenis van de arbeiders krijgt iedereen er één voor een dag werken (Matteüs 20:2). Kijk eens naar het verschil tussen die twee bedragen: het zilver in de munt is bijna niets waard, maar je verdiende er wél een hele dag mee." },
    { item: "<span class=\"naslag-term\">As</span> — € 10 à 12, een zestiende dagloon, ongeveer een half uur werken. Voor één as kocht je twee mussen, en tóch vergeet God er geen enkele van (Matteüs 10:29). In het Grieks heet deze munt assarion. In veel Bijbels staat \"stuiver\" of \"duit\"." },
    { item: "<span class=\"naslag-term\">Quadrans</span> — € 2 à 3, een vierenzestigste dagloon, ongeveer tien minuten werken (Matteüs 5:26)." },
    { item: "<span class=\"naslag-term\">Lepton</span> — € 1 à 2, een honderdachtentwintigste dagloon. Het allerkleinste muntje dat er bestond. De arme weduwe gaf er twee, en Jezus zei dat zij het meeste had gegeven (Marcus 12:42, Lucas 21:2). Twee lepta zijn samen precies een quadrans. In oudere Nederlandse Bijbels heet dit muntje een penning. Maar diezelfde Bijbels noemen ook de denarie een penning, en de quadrans, en het muntje waarvoor je twee mussen kocht. Dat komt doordat penning daar geen naam van één munt is, maar gewoon 'geldstuk' betekent — een keuze die vierhonderd jaar geleden goed te begrijpen was, omdat de vertalers de muntnamen gebruikten die hun lezers kenden. In de kanttekeningen leggen ze er netjes bij uit wat elke munt waard was. Alleen wie de kanttekening niet leest, denkt al snel dat het overal om kleingeld gaat." },
    { item: "<span class=\"naslag-term\">Grieks geld</span> — het geld van de handel" },
    { item: "<span class=\"naslag-term\">Drachme</span> — € 150 à 200, ongeveer één dagloon. Naar zilver: ongeveer € 8. Bijna hetzelfde waard als een denarie. De vrouw die haar tiende drachme kwijtraakt, keert daarvoor haar hele huis om (Lucas 15:8)." },
    { item: "<span class=\"naslag-term\">Didrachme</span> — € 300 à 400, twee daglonen. Naar zilver: ongeveer € 16. Twee drachmen, en precies het bedrag van de tempelbelasting (Matteüs 17:24)." },
    { item: "<span class=\"naslag-term\">Stater</span> — € 600 à 800, vier daglonen. Naar zilver: ongeveer € 30. Petrus vond er een in de bek van een vis, genoeg voor de tempelbelasting van hen beiden (Matteüs 17:27)." },
    { item: "<span class=\"naslag-term\">Pond</span> — € 15.000 à 20.000, honderd daglonen: ruim drie maanden werken. Naar zilver: ongeveer € 800. Tien dienaren krijgen er elk één om mee te handelen (Lucas 19:13). In het Grieks heet dit een mina." },
    { item: "<span class=\"naslag-term\">Talent</span> — € 900.000 à 1,2 miljoen, zesduizend daglonen. Naar zilver: ongeveer € 48.000. De allergrootste geldmaat. Daar zou een arbeider vijftien tot twintig jaar voor moeten werken. Als gewicht aan zilver of goud was een talent ongeveer 33 kilo (van zo'n 20 tot 40 kilo). In de gelijkenis van de onbarmhartige dienaar is iemand tienduizend talenten schuldig (Matteüs 18:24). Dat is met opzet een onmogelijk bedrag: je zou er tweehonderdduizend jaar voor moeten werken." },
    { item: "<span class=\"naslag-term\">Tempelgeld</span> — geld apart" },
    { item: "Iedere volwassen man betaalde één keer per jaar een halve sikkel voor de tempel. Die regel staat al in het Oude Testament (Exodus 30:13). In de tijd van Jezus was dat bedrag twee daglonen: € 300 à 400. In het Nieuwe Testament heet die belasting daarom de didrachme — twee drachmen (Matteüs 17:24)." },
    { item: "Maar betalen mocht alleen met één bepaald soort zilvergeld. Pelgrims kwamen met munten uit allerlei landen; daarom zaten er geldwisselaars op het tempelplein, en daarom kon je er niet omheen (Matteüs 21:12)." },
    { item: "Wat de Bijbel er niet bij zegt: met wélk geld er dan wél betaald werd. Archeologen hebben ontdekt dat het meestal zilvergeld uit de stad Tyrus was, omdat dat het zuiverste zilver had. Maar die naam staat niet in de Bijbel zelf. Opvallend: op die munten stond zelf een afbeelding van een heidense god. Het ging dus niet om het plaatje, maar om het zilver." },
];

const ONTDEK_MATEN = [
    { kop: "Lengte" },
    { item: "<span class=\"naslag-term\">El</span> — ongeveer 45 centimeter, zo lang als de afstand van je elleboog tot je vingertoppen. Daar komt de naam vandaan. Omdat niet iedereen even lange armen heeft, was hij niet overal precies gelijk." },
    { item: "<span class=\"naslag-term\">Stadie</span> — een afstandsmaat van ongeveer 185 meter. Emmaüs lag zo'n zestig stadiën van Jeruzalem: ruim elf kilometer." },
    { item: "<span class=\"naslag-term\">Mijl</span> — de Romeinse mijl was ongeveer 1.500 meter (anderhalve kilometer), oorspronkelijk duizend dubbele passen van een soldaat. Jezus zei: als iemand je dwingt één mijl mee te gaan, ga er dan twee." },
    { kop: "Inhoud" },
    { noot: "Hier weten we het minder zeker: er bestond geen officiële standaard, en de potten en vaten van toen waren niet allemaal even groot." },
    { item: "<span class=\"naslag-term\">Vat</span> (Grieks: batos, van het Hebreeuwse bat) — ongeveer 22 liter, zo'n twee volle emmers. Sommige geleerden komen hoger uit." },
    { item: "<span class=\"naslag-term\">Kor</span> — de grootste inhoudsmaat: tien vaten, dus ongeveer 220 liter. In Nederlandse Bijbels staat op die plaats meestal 'zakken'." },
    { item: "<span class=\"naslag-term\">Seah</span> — een derde van een vat, zo'n 7 liter, al lopen de schattingen uiteen. Drie seah meel was genoeg om voor een heleboel mensen brood te bakken." },
    { item: "<span class=\"naslag-term\">Korenmaat</span> — een bak of mand waar ongeveer negen liter graan in kon, ongeveer een emmer vol. Jezus zei dat je een lamp niet ónder de korenmaat zet, maar erop, zodat iedereen het licht ziet." },
    { item: "<span class=\"naslag-term\">Metreet</span> — een grote inhoudsmaat van ongeveer 39 liter. De stenen kruiken op de bruiloft in Kana hielden er elk twee of drie van — dus zo'n 80 tot 120 liter per kruik." },
];

const ONTDEK_TIJD = [
    { kop: "Tijd" },
    { item: "<span class=\"naslag-term\">Uren</span> — de tijdsaanduidingen in de Bijbel werken anders dan onze moderne klok. In de tijd van Jezus begon de dag bij zonsopgang, ongeveer om 6.00 uur. De tijd tot zonsondergang werd in twaalf uren verdeeld. De tabel laat zien rond welk tijdstip op onze klok elk Bijbels uur ongeveer uitkomt." },
    { tabel: { koppen: ["Bijbels uur", "Onze tijd (ongeveer)"], rijen: [["1e uur", "07.00"], ["2e uur", "08.00"], ["3e uur", "09.00"], ["4e uur", "10.00"], ["5e uur", "11.00"], ["6e uur", "12.00"], ["7e uur", "13.00"], ["8e uur", "14.00"], ["9e uur", "15.00"], ["10e uur", "16.00"], ["11e uur", "17.00"], ["12e uur", "18.00 (zonsondergang)"]] } },
    { noot: "Goed om te weten: bij de Romeinen en de Joden begon het eerste uur eigenlijk al bij zonsopgang, rond 6.00 uur. In de meeste bijbelcommentaren wordt het eerste uur echter rond 7.00 uur gerekend. Wij volgen hier die gangbare indeling — zo blijven de bekende voorbeelden hieronder (zoals het negende uur rond 15.00 uur) goed kloppen." },
    { item: "<span class=\"naslag-term\">Bekende voorbeelden</span>" },
    { item: "<span class=\"naslag-term\">Het derde uur</span> → ongeveer 9.00 uur. Bij Pinksteren zei Petrus: \"Het is pas het derde uur van de dag\" (Handelingen 2:15)." },
    { item: "<span class=\"naslag-term\">Het zesde uur</span> → ongeveer 12.00 uur. Rond het middaguur sprak Jezus bij de put met de Samaritaanse vrouw (Johannes 4:6)." },
    { item: "<span class=\"naslag-term\">Het negende uur</span> → ongeveer 15.00 uur. Rond dit uur stierf Jezus aan het kruis (Matteüs 27:46-50). Het was ook een vast uur van gebed: Petrus en Johannes gingen toen naar de tempel (Handelingen 3:1)." },
    { item: "<span class=\"naslag-term\">Zomer en winter: niet elk uur even lang</span>" },
    { item: "Er zit behoorlijk wat verschil tussen zomer en winter. Israël ligt ongeveer op dezelfde breedtegraad als Zuid-Spanje en Noord-Afrika. Daardoor zijn de verschillen kleiner dan in Nederland, maar nog steeds duidelijk merkbaar. Voor Jeruzalem gelden ongeveer deze tijden:" },
    { tabel: { koppen: ["Periode", "Zonsopgang", "Zonsondergang"], rijen: [["Winter (± 21 dec)", "± 06.35", "± 16.40"], ["Lente (± 21 mrt)", "± 05.45", "± 17.55"], ["Zomer (± 21 jun)", "± 05.30", "± 19.45"], ["Herfst (± 21 sep)", "± 06.20", "± 18.20"]] } },
    { item: "De daglengte varieert dus van ongeveer 10 uur in de winter tot ruim 14 uur in de zomer. En omdat men die daglengte altijd in twaalf gelijke delen verdeelde, duurde één \"uur\" in de winter ongeveer 50 minuten en in de zomer ongeveer 70 minuten. Daarom viel bijvoorbeeld het \"negende uur\" niet altijd precies op 15.00 uur volgens onze klok, maar ergens midden tot laat in de middag." },
    { item: "<span class=\"naslag-term\">Voorbeeld: het negende uur</span>" },
    { tabel: { koppen: ["", "Winter (dag ± 10 uur)", "Zomer (dag ± 14 uur)"], rijen: [["Zonsopgang", "06.35", "05.30"], ["Eén Bijbels uur", "± 50 min", "± 70 min"], ["Negende uur", "± 14.05", "± 15.55"]] } },
    { item: "<span class=\"naslag-term\">Nachtwaak</span> — in de tijd van Jezus verdeelden de Romeinen de nacht in vier \"wachten\" van ongeveer drie uur, samen van zes uur 's avonds tot zes uur 's ochtends. Wachters losten elkaar per wacht af — vandaar de naam." },
    { tabel: { koppen: ["Nachtwaak", "Tijd"], rijen: [["1e", "18.00 – 21.00 uur"], ["2e", "21.00 – 24.00 uur"], ["3e", "24.00 – 3.00 uur"], ["4e", "3.00 – 6.00 uur"]] } },
    { item: "De vierde nachtwaak is op het einde van de nacht, vlak voor zonsopgang. Toen Jezus over het water naar de leerlingen liep, was het de vierde nachtwaak (Matteüs 14:25): het moet dus na 3.00 uur zijn geweest, ergens tot aan zonsopgang. In het Oude Testament kende men er nog maar drie, van zo'n vier uur." },
];

// --- Verborgen patronen: de drie artikelen ----------------------------------
// De id's zijn ongewijzigd overgenomen: verborgenSchatVragen verwijst ernaar
// via catecheseId, en die pool blijft ongemoeid.
const ONTDEK_PATRONEN = [
    {
        id: "verborgen-getallen-153",
        naam: "De 153 vissen",
        type: "artikel",
        inhoud: [
            { item: "Na Zijn opstanding liet Jezus zich aan Zijn leerlingen zien bij het meer. Ze hadden de hele nacht gevist en niets gevangen. Op Jezus' woord gooiden ze het net nóg een keer uit — en nu zat het zó vol dat ze het bijna niet aan land kregen. Toen ze de vissen telden, waren het er precies honderddrieënvijftig. En het mooie: hoe vol het net ook zat, het scheurde niet (Johannes 21)." },
            { item: "Waarom zou Johannes zo'n precies getal opschrijven? Johannes is namelijk een schrijver die van verborgen lagen houdt: in zijn evangelie zit vaak een diepere betekenis onder de oppervlakte. En bij dit getal hebben uitleggers door de eeuwen heen iets bijzonders gezien." },
            { item: "De kerkvader Hiëronymus schrijft dat men in zijn tijd geloofde dat er precies 153 soorten vissen in de zee bestonden — élke soort die er was. Het beeld werd dan: het net van het evangelie haalt mensen binnen uit élk volk, uit de hele wereld. De blijde boodschap is niet voor één groep, maar voor iedereen." },
            { item: "En dat het net niet scheurde? Ook dat lazen ze als een boodschap: in dat ene net is plaats voor allemaal, en er gaat niemand verloren." },
            { item: "Sommige uitleggers, zoals Augustinus, keken naar het getal zelf. 153 is namelijk de optelsom van alle getallen van 1 tot en met 17 (1 + 2 + 3 + … + 17 = 153). En 17, zeiden zij, is 10 + 7: de tien geboden plus de zeven gaven van Gods Geest. Zo werd 153 een teken van álle mensen die bij God horen — door Zijn wet én door Zijn genade." },
            { item: "Er zit zelfs nog een wiskundig wonder in: 153 is óók gelijk aan 1×1×1 + 5×5×5 + 3×3×3 (dat is 1 + 125 + 27). Een getal dat zó keurig in elkaar past, voelt niet zomaar gekozen." },
            { item: "Belangrijk om te weten: deze betekenissen staan niet allemaal letterlijk in de Bijbel — het zijn uitleggingen die door de eeuwen heen zijn ontstaan. Maar ze laten prachtig zien hoe gelovigen in zo'n klein detail een grote boodschap ontdekten: het goede nieuws van Jezus is bestemd voor de hele wereld." },
        ]
    },
    {
        id: "verborgen-patronen-paulus-brieven",
        naam: "De verborgen schat in de brieven van Paulus",
        type: "artikel",
        inhoud: [
            { item: "Heb je je weleens afgevraagd waarom de brieven van Paulus in de Bijbel in deze volgorde staan? Het is niet de volgorde waarin hij ze schreef. De brieven zijn ongeveer gerangschikt op lengte: de langste (de brief aan de Romeinen) staat vooraan, en zo wordt het steeds korter, tot het kleine briefje aan Filemon achteraan. Eerst komen de brieven aan gemeenten, daarna de brieven aan personen." },
            { item: "Maar er gebeurt iets moois als je de brieven anders leest — niet op lengte, maar op tijd. Op de volgorde waarin Paulus ze schreef, van zijn eerste jaren als apostel tot vlak voor zijn dood. Dan ontdek je een patroon dat je anders nooit zou zien. Een soort verborgen schat." },
            { item: "Vroeg in zijn leven, in de eerste brief aan de Korintiërs (rond het jaar 54), schrijft Paulus: \"Want ik ben de minste van de apostelen.\" (1 Korintiërs 15:9). De minste van de apostelen — dat is al nederig. En er zijn maar twaalf apostelen, dus dat is nog een kleine groep om de laagste van te zijn." },
            { item: "Jaren later, als hij gevangenzit in Rome, schrijft hij in de brief aan de Efeziërs (rond het jaar 60): \"Mij, de allerminste van alle gelovigen…\" (Efeziërs 3:8). Nu is hij niet meer de minste van de apostelen, maar de minste van alle gelovigen. De groep is veel groter geworden, en Paulus zet zichzelf onderaan." },
            { item: "En helemaal aan het einde van zijn leven, in de eerste brief aan Timoteüs (rond het jaar 64), schrijft hij: \"Christus Jezus is in de wereld gekomen om zondaars te redden, en ik ben de grootste van hen.\" (1 Timoteüs 1:15). Niet meer de minste apostel, niet meer de minste gelovige, maar de grootste van alle zondaars." },
            { item: "Zie je het patroon? Hoe ouder Paulus werd en hoe dichter hij bij God leefde, hoe kleiner hij zichzelf maakte. Dat lijkt misschien gek — je zou denken dat iemand die zoveel voor God deed juist trotser zou worden. Maar bij Paulus is het andersom. Hoe meer hij Gods liefde leerde kennen, hoe duidelijker hij zag hoe groot die genade voor hém was." },
            { item: "En let op iets belangrijks: Paulus bleef gewoon apostel. Hij heeft die taak nooit weggegooid. Hij hield twee dingen tegelijk vast — \"ik ben een apostel van Jezus Christus\" én \"ik ben de grootste zondaar\". Dat spreekt elkaar niet tegen. Je mag weten wie je in God bent, en tegelijk klein blijven voor Hem." },
            { item: "Paulus zegt dit nergens hardop. Hij schrijft niet: \"let op, ik word steeds nederiger.\" Je ontdekt het pas als je zijn brieven naast elkaar legt op volgorde van tijd. Daarom is het echt een verborgen schat: hij ligt verstopt in de volgorde, en je vindt hem alleen als je goed zoekt." },
            { item: "Eén ding om eerlijk bij te zeggen: de jaartallen hierboven zijn ongeveer — geleerden weten niet op de dag nauwkeurig wanneer Paulus elke brief schreef. En dat Paulus \"steeds nederiger\" werd, is iets wat wij ontdekken als we de brieven op tijd ordenen; het is een prachtige ontdekking, geen regel die zo in de Bijbel staat. Maar de drie teksten zijn er echt, en ze zijn in deze volgorde geschreven. Dat maakt het zo bijzonder." },
            { item: "Word jij van binnen groter of kleiner naarmate je meer leert? Paulus laat zien dat echt dichtbij God komen je juist nederig maakt — niet omdat je niks waard bent, maar omdat je steeds beter ziet hoe groot Gods liefde is." },
        ]
    },
    {
        id: "verborgen-patronen-sandwich",
        naam: "De sandwich-techniek van Marcus",
        type: "artikel",
        inhoud: [
            { item: "Marcus blijkt een knappe verteller. Hij begint een verhaal, schuift er een tweede verhaal tussen, en pakt dan de draad van het eerste weer op — net als twee boterhammen met beleg ertussen. Geleerden noemen dit de sandwich-techniek (met een moeilijk woord: intercalatie)." },
            { item: "Het mooiste inzicht: de nadruk ligt meestal op het verhaal ín het midden — net als bij een echte sandwich is het beleg waar het om draait. Dat binnenste verhaal is vaak de sleutel tot de betekenis, en de twee verhalen eromheen helpen je dat te begrijpen." },
            { item: "Bij Jaïrus en de zieke vrouw (Marcus 5) staat zo het geloof van de vrouw in het midden, met een knipoog: het getal twaalf komt in beide verhalen terug — de vrouw is twaalf jaar ziek, het meisje twaalf jaar oud. Een ander bekend voorbeeld is de tempelreiniging, ingeklemd tussen de vervloeking en het verdorren van een vijgenboom (Marcus 11)." },
            { item: "Zo blijkt dat Marcus zijn evangelie zorgvuldig heeft opgebouwd — niet als losse verhalen, maar als één doordacht geheel. Kun jij nog een sandwich vinden als je Marcus leest?" },
        ]
    },
];

// --- Verborgen Schat (op slot) ----------------------------------------------
// De eerste twaalf komen één op één uit de oude naslagpagina en volgen de
// volgorde van de vragen 1 t/m 12. Daarna vier onderwerpen voor de vragen
// 13 t/m 16, die op de oude pagina ontbraken: twee verwijzingen naar een
// bestaand artikel, en twee plekken waar de tekst nog geschreven moet worden.
const ONTDEK_SCHAT = [
    { id: "van-wie-was-het-huis-met-de-bovenzaal-va", naam: "Van wie was het huis met de bovenzaal van het Laatste Avondmaal?", type: "artikel", inhoud: [ { item: "Hier moeten we eerlijk zijn — en juist dat maakt het een echte schat. De evangeliën noemen de eigenaar namelijk níet. Jezus stuurt Zijn leerlingen achter \"een man met een kruik water\" aan; die brengt hen naar een huis met een grote bovenzaal, maar een naam krijgen we niet (Marcus 14, Lucas 22). In een kerk in Jeruzalem staat een inscriptie uit de zesde eeuw die een huis aanwijst als dat van Maria, de moeder van Johannes Marcus. Sindsdien wordt die bovenzaal vaak met haar huis verbonden — ook omdat de eerste christenen later juist bij háár thuis bij elkaar kwamen (Handelingen 12:12). Het mooie om te weten is dus het verschil: wat zwart-op-wit in de Bijbel staat (een naamloze gastheer) en wat er later bij is gekomen (het huis van Maria). Allebei waardevol, maar het is goed om ze uit elkaar te houden." } ] },
    { id: "wat-betekent-apocalyps-eigenlijk", naam: "Wat betekent \"apocalyps\" eigenlijk?", type: "artikel", inhoud: [ { item: "Veel mensen denken bij \"apocalyps\" meteen aan het einde van de wereld, aan rampen en ondergang. Maar het Griekse woord <em>apokalypsis</em> betekent iets heel anders: \"onthulling\" of \"openbaring\" — het wegtrekken van een sluier, zodat je ziet wat eerst verborgen was. Daarom heet het laatste Bijbelboek in het Nederlands ook \"Openbaring\". Het wil dus niet vooral angst aanjagen, maar iets láten zien. En dat is precies waarom dit zo goed bij de Verborgen Schat past: een verborgen schat onthullen is letterlijk wat een apocalyps doet." } ] },
    { id: "waarom-noemt-jezus-zichzelf-de-alfa-en-d", naam: "Waarom noemt Jezus zichzelf \"de Alfa en de Omega\"?", type: "artikel", inhoud: [ { item: "Alfa is de eerste letter van het Griekse alfabet, omega de laatste — een beetje zoals onze A en Z. Door zichzelf zo te noemen zegt Jezus: Ik ben er vanaf het allereerste begin én tot aan het einde van alles. Er is geen moment dat buiten Hem valt; Hij staat aan het begin van het verhaal én aan het slot. Zo zegt Hij in twee letters iets enorms over wie Hij is." } ] },
    { id: "wie-wordt-in-openbaring-het-lam-genoemd", naam: "Wie wordt in Openbaring \"het Lam\" genoemd, en waarom juist een lam?", type: "artikel", inhoud: [ { item: "Met \"het Lam\" wordt steeds Jezus bedoeld. Een lam is een kwetsbaar, zachtmoedig dier, en het werd vroeger gebruikt als offerdier — het beeld wijst dus naar Jezus die zichzelf opofferde. Het verrassende is dat juist dit geofferde Lam in Openbaring de grote overwinnaar is. Niet de sterkste of de hardste wint, maar het Lam dat zichzelf gaf. Die omkering — kwetsbaarheid die overwint — is een van de diepste lagen van het boek." } ] },
    { id: "waar-staat-het-getal-zeven-symbolisch-vo", naam: "Waar staat het getal zeven symbolisch voor?", type: "artikel", inhoud: [ { item: "In Openbaring kom je zeven overal tegen: zeven gemeenten, zeven zegels, zeven bazuinen, zeven schalen. Dat is geen toeval. In de Bijbel staat zeven voor volheid, voor \"helemaal compleet\" — denk aan de zeven dagen waarin de schepping af was. Het gaat dus niet om precies tellen, maar om volledigheid. Wie dat doorheeft, leest Openbaring anders: het wil zeggen dat Gods plan helemaal compleet wordt, tot in alle hoeken." } ] },
    { id: "hoe-eindigt-de-bijbel-in-openbaring", naam: "Hoe eindigt de Bijbel in Openbaring?", type: "artikel", inhoud: [ { item: "Niet met ondergang, maar met hoop. In de laatste hoofdstukken komt er een nieuwe hemel en een nieuwe aarde, waar God zelf bij de mensen woont en waar geen tranen, dood of pijn meer zijn. En er gebeurt iets moois: de levensboom uit het paradijs, helemaal aan het begin van de Bijbel, keert terug. Zo komt het hele verhaal rond — het paradijs dat in Genesis verloren ging, wordt aan het einde hersteld. De Bijbel sluit zich als een grote cirkel." } ] },
    { id: "wat-betekent-een-tijd-tijden-en-een-halv", naam: "Wat betekent \"een tijd, tijden en een halve tijd\"?", type: "artikel", inhoud: [ { item: "Het klinkt cryptisch, maar je kunt het gewoon uitrekenen: een \"tijd\" is een jaar, \"tijden\" is twee jaar, en een \"halve tijd\" een half jaar — samen drieënhalf jaar. De Bijbel noemt diezelfde periode elders met andere woorden: 42 maanden, of 1260 dagen. En de uitdrukking dook eeuwen eerder al op in het boek Daniël — Openbaring pakt dat beeld bewust weer op." } ] },
    { id: "waar-komen-de-vier-levende-wezens-vandaa", naam: "Waar komen de vier levende wezens vandaan?", type: "artikel", inhoud: [ { item: "De vier wezens rond Gods troon — een leeuw, een rund, een mens en een arend — komen uit een eeuwenoud visioen van de profeet Ezechiël. Het bijzondere: deze vier gezichten werden later de symbolen van de vier evangelisten. De leeuw hoort bij Marcus, het rund bij Lucas, de mens bij Matteüs en de arend bij Johannes. Precies de vier die je in dit spel als trofeeën kunt verdienen!" } ] },
    { id: "de-boom-des-levens-begin-en-einde", naam: "De boom des levens — begin en einde", type: "artikel", inhoud: [ { item: "De Bijbel begint en eindigt bij dezelfde boom. In het paradijs (Genesis) staat de boom des levens, en helemaal aan het eind, in het nieuwe Jeruzalem (Openbaring), staat hij er weer — met bladeren tot genezing van de volken. Tussen die twee bomen in speelt het hele verhaal van de Bijbel zich af. Let op: in het paradijs stonden twee bijzondere bomen; alleen de boom des levens komt aan het eind terug, niet de boom van kennis van goed en kwaad." } ] },
    { id: "de-zeven-gemeenten", naam: "De zeven gemeenten", type: "artikel", inhoud: [ { item: "Openbaring begint als een brief aan zeven echte gemeenten in Klein-Azië (het huidige Turkije): Efeze, Smyrna, Pergamum, Tyatira, Sardis, Filadelfia en Laodicea. Het getal zeven is geen toeval — het staat in de Bijbel voor volheid. Door aan zéven gemeenten te schrijven, schrijft Johannes eigenlijk aan de hele kerk." } ] },
    { id: "het-nieuwe-jeruzalem", naam: "Het nieuwe Jeruzalem", type: "artikel", inhoud: [ { item: "Aan het slot van Openbaring daalt een schitterende stad uit de hemel neer: het nieuwe Jeruzalem. Het mooiste is niet het goud of de edelstenen, maar wat erbij gezegd wordt: God woont nu voorgoed bij de mensen, en Hij wist alle tranen weg. Geen dood, geen verdriet en geen pijn meer. Daar loopt het hele verhaal van de Bijbel op uit." } ] },
    // Eén canonieke versie: het artikel in Verborgen patronen.
    { id: "de-sandwich-techniek-van-marcus", naam: "De sandwich-techniek van Marcus", verwijstNaar: "verborgen-patronen-sandwich" },

    // Vragen 13 en 14: het artikel bestaat al in Verborgen patronen.
    { id: "de-153-vissen", naam: "De 153 vissen", verwijstNaar: "verborgen-getallen-153" },
    { id: "de-brieven-van-paulus", naam: "De volgorde van de brieven van Paulus", verwijstNaar: "verborgen-patronen-paulus-brieven" },

    // Vragen 15 en 16: plek gemaakt, tekst nog te schrijven.
    { id: "het-oor-van-malchus", naam: "Het oor van Malchus", type: "artikel",
      inhoud: [ { item: "Deze uitleg wordt nog geschreven." } ] },
    { id: "de-brief-aan-de-hebreeen", naam: "De brief aan de Hebree\u00ebn", type: "artikel",
      inhoud: [ { item: "Deze uitleg wordt nog geschreven." } ] },

    // Vraag 17: het poortje-verhaal bij Marcus 10:25-27.
    { id: "het-oog-van-de-naald", naam: "Waarom \"het oog van de naald\" waarschijnlijk geen poortje was", type: "artikel",
      inhoud: [
          { item: "Je hoort het vaak: het oog van de naald zou een laag poortje in de muur van Jeruzalem zijn geweest, waar een kameel alleen doorheen kon als hij eerst alle bagage aflegde. Een mooi beeld — je moet je spullen loslaten om erdoor te komen." },
          { item: "Toch klopt er iets niet. Als je de oudste christelijke uitleggers erop naslaat, mensen als Origenes, Chrysostomus en Augustinus, dan bespreken die deze tekst uitgebreid, maar noemt geen van hen een poort. Het verhaal duikt pas veel later op, in preken." },
          { item: "Wat Jezus waarschijnlijk juist bedoelde, is dat het beeld ónmogelijk is. Een enorme kameel door een piepklein naaldgaatje: dat kán niet. En dat is precies de bedoeling. De leerlingen schrikken en vragen: wie kan er dan nog gered worden? Jezus antwoordt: bij mensen is dit onmogelijk, maar bij God is alles mogelijk." }
      ] },
];
